In [ ]:
import os
import sys
parent_dir = "/Midgard/home/farzantn/phd/Olfaction/MoLFormer_N2024"
sys.path.append(parent_dir)
parent_dir="/Midgard/home/farzantn/mambaforge/envs/MolTran_CUDA11_cuda/lib/python3.8"
sys.path.append(parent_dir)

In [2]:

import scipy.io as sio
parent_dir="/Midgard/home/farzantn/mambaforge/envs/MolTran_CUDA11_cuda/lib/python3.8"
sys.path.append(parent_dir)
path='/local_storage/datasets/farzaneh/Olfaction/fmri_test/'
from utils.ridge_tools import *
import pandas as pd
import ast
base_directory = ''
import scipy
from utils.random_methods import *

# finding fine-grained and coarse-level similarity between molecules

In [3]:
sagar_ds = pd.read_csv('/local_storage/datasets/farzaneh/alignment_olfaction_datasets/curated_datasets/mols_datasets/curated_sagar_subjects_nonaminus.csv')

In [4]:
sagar_ds

mol index  Intensity  Pleasantness     Fishy     Burnt      Sour  \
0            0  -0.855639     -0.706475 -1.000000 -1.000000 -0.829167   
1            1  -0.842105     -0.248921 -0.971084 -1.000000 -0.908333   
2            2  -1.000000      0.191581 -1.000000 -1.000000 -0.642413   
3            3  -1.000000      0.014388 -0.682525 -1.000000 -1.000000   
4            4  -0.016541      0.789928 -1.000000 -0.994764 -0.991667   
..         ...        ...           ...       ...       ...       ...   
475        155  -0.281250     -0.250000 -0.500000 -0.391667 -0.462500   
476        156  -0.508333     -0.418750 -1.000000 -0.741667 -0.950000   
477        157  -0.695833     -0.241667 -1.000000 -0.381250 -0.945833   
478        158  -0.187500     -0.277083 -0.250000 -0.189583 -0.641667   
479        159  -0.500000     -0.108333 -0.500000 -0.435417 -0.466667   

      Decayed     Musky    Fruity    Sweaty  ...    Floral     Sweet  \
0   -0.958333 -0.364355 -0.609139 -0.483075  ... -0.422096 -0.558333   
1   -0.479167  0.008333 -0.508333 -0.478701  ... -0.576163  0.462500   
2   -1.000000 -0.372387 -1.000000 -0.438162  ... -0.988669 -0.302147   
3   -0.525000 -0.380498 -0.761828 -1.000000  ... -1.000000 -0.430966   
4   -0.508333 -1.000000  0.908333  0.303483  ... -0.372412 -0.108333   
..        ...       ...       ...       ...  ...       ...       ...   
475 -0.250000 -0.500000 -0.316667 -0.250000  ... -0.443750 -0.429167   
476 -1.000000 -1.000000 -1.000000 -0.983333  ... -0.422917 -0.652083   
477 -0.500000 -0.831250 -0.950000 -1.000000  ... -0.345833 -0.816667   
478 -0.250000 -0.197917 -0.427083 -0.750000  ... -0.191667 -0.133333   
479 -0.500000 -0.766667 -0.393750 -0.250000  ... -0.458333 -0.370833   

         Warm    Bakery     Spicy    detect      cid  \
0   -0.222780 -0.662480 -0.797087  0.200000      126   
1    0.562791  0.642857 -1.000000  0.466667      177   
2   -1.000000 -0.622368 -0.776247  0.166667      196   
3   -0.609302 -0.660859 -0.989691  0.066667      239   
4    0.339535  0.044643 -0.774490  0.766667      240   
..        ...       ...       ...       ...      ...   
475 -0.552083 -0.920833 -0.404167  0.370370   643820   
476 -0.677083 -0.554167 -0.793750  0.740741  3578033   
477 -0.304167 -0.375000 -1.000000  0.629630  5365027   
478 -0.177083 -0.681250 -0.529167  0.333333  5366244   
479 -0.612500 -0.252083 -0.252083  0.222222  6999977   

                        IsomericSMILES                 nonStereoSMILES subject  
0                    C1=CC(=CC=C1C=O)O                  O=Cc1ccc(O)cc1       1  
1                                 CC=O                            CC=O       1  
2                   C(CCC(=O)O)CC(=O)O                O=C(O)CCCCC(=O)O       1  
3                          C(CN)C(=O)O                       NCCC(=O)O       1  
4                     C1=CC=C(C=C1)C=O                     O=Cc1ccccc1       1  
..                                 ...                             ...     ...  
475               CC(=CCC/C(=C\CO)/C)C               CC(C)=CCCC(C)=CCO       3  
476               CC1=CC=C(O1)C(C)CC=O              Cc1ccc(C(C)CC=O)o1       3  
477                      CCCCCC/C=C\CO                     CCCCCCC=CCO       3  
478  CC(C)CCCC(C)CCCC(C)CCC/C(=C/CO)/C  CC(=CCO)CCCC(C)CCCC(C)CCCC(C)C       3  
479                CCCCOC(=O)[C@H](C)O                 CCCCOC(=O)C(C)O       3  

[480 rows x 21 columns]

In [13]:
# selected_columns = sagar_ds.loc[:, 'Fishy':'Spicy']
# selected_columns

Fishy     Burnt      Sour   Decayed     Musky    Fruity    Sweaty  \
0   -1.000000 -1.000000 -0.829167 -0.958333 -0.364355 -0.609139 -0.483075   
1   -0.971084 -1.000000 -0.908333 -0.479167  0.008333 -0.508333 -0.478701   
2   -1.000000 -1.000000 -0.642413 -1.000000 -0.372387 -1.000000 -0.438162   
3   -0.682525 -1.000000 -1.000000 -0.525000 -0.380498 -0.761828 -1.000000   
4   -1.000000 -0.994764 -0.991667 -0.508333 -1.000000  0.908333  0.303483   
..        ...       ...       ...       ...       ...       ...       ...   
475 -0.500000 -0.391667 -0.462500 -0.250000 -0.500000 -0.316667 -0.250000   
476 -1.000000 -0.741667 -0.950000 -1.000000 -1.000000 -1.000000 -0.983333   
477 -1.000000 -0.381250 -0.945833 -0.500000 -0.831250 -0.950000 -1.000000   
478 -0.250000 -0.189583 -0.641667 -0.250000 -0.197917 -0.427083 -0.750000   
479 -0.500000 -0.435417 -0.466667 -0.500000 -0.766667 -0.393750 -0.250000   

         Cool    Floral     Sweet      Warm    Bakery     Spicy  
0   -0.618216 -0.422096 -0.558333 -0.222780 -0.662480 -0.797087  
1   -0.604466 -0.576163  0.462500  0.562791  0.642857 -1.000000  
2   -1.000000 -0.988669 -0.302147 -1.000000 -0.622368 -0.776247  
3   -1.000000 -1.000000 -0.430966 -0.609302 -0.660859 -0.989691  
4   -0.544554 -0.372412 -0.108333  0.339535  0.044643 -0.774490  
..        ...       ...       ...       ...       ...       ...  
475 -0.785417 -0.443750 -0.429167 -0.552083 -0.920833 -0.404167  
476 -0.885417 -0.422917 -0.652083 -0.677083 -0.554167 -0.793750  
477 -0.172917 -0.345833 -0.816667 -0.304167 -0.375000 -1.000000  
478 -0.187500 -0.191667 -0.133333 -0.177083 -0.681250 -0.529167  
479 -0.500000 -0.458333 -0.370833 -0.612500 -0.252083 -0.252083  

[480 rows x 13 columns]

In [16]:
Ethyl_propionate =sagar_ds[sagar_ds['cid']== 7749]
Ethyl_butanoate=sagar_ds[sagar_ds['cid']== 7762]
# Ethyl_propionate = Ethyl_propionate.loc[:, 'Fishy':'Spicy']
# Ethyl_propionate = Ethyl_propionate.to_numpy()

In [18]:
for subject in [1,2,3]:
    Ethyl_propionate_s = Ethyl_propionate[Ethyl_propionate['subject']==subject]
    Ethyl_propionate_s = Ethyl_propionate_s.loc[:, 'Fishy':'Spicy']
    Ethyl_propionate_s = Ethyl_propionate_s.to_numpy()
    
    
    Ethyl_butanoate_s = Ethyl_butanoate[Ethyl_butanoate['subject']==subject]
    Ethyl_butanoate_s = Ethyl_butanoate_s.loc[:, 'Fishy':'Spicy']
    Ethyl_butanoate_s = Ethyl_butanoate_s.to_numpy()
    
    _, index =find_coarse_similarity(Ethyl_propionate_s, Ethyl_butanoate_s)
    print(index)
    
    
    

[5]
[1]
[1]


In [29]:
# average over all rows of a dataframe pandas
Ethyl_propionate_selected = Ethyl_propionate.loc[:, 'Fishy':'Spicy']
Ethyl_propionate_avg  = Ethyl_propionate_selected.mean(axis=0)

Ethyl_butanoate_selected = Ethyl_butanoate.loc[:, 'Fishy':'Spicy']
Ethyl_butanoate_avg  = Ethyl_butanoate_selected.mean(axis=0)

In [6]:
Ethyl =sagar_ds[(sagar_ds['cid']== 7749) | (sagar_ds['cid']== 7762)]

In [11]:
Ethyl = Ethyl.groupby('cid').mean(numeric_only=True).reset_index()

In [13]:
Ethyl_butanoate =  Ethyl[Ethyl['cid']== 7762]
Ethyl_butanoate = Ethyl_butanoate.loc[:, 'Fishy':'Spicy'].to_numpy()

Ethyl_propionate =  Ethyl[Ethyl['cid']== 7749]
Ethyl_propionate = Ethyl_propionate.loc[:, 'Fishy':'Spicy'].to_numpy()


_, index =find_coarse_similarity(Ethyl_butanoate, Ethyl_propionate)
print(index)

[12]


In [14]:
Ethyl_butanoate

array([[-0.72314815, -0.83769634, -0.32106481, -0.3212963 , -0.55208333,
         0.49861111, -0.71443823, -0.76412037, -0.44643663, -0.14236111,
        -0.56296296, -0.72546296, -0.93888889]])

In [12]:

Ethyl_butanoate = Ethyl_butanoate.loc[:, 'Fishy':'Spicy']
Ethyl_butanoate = Ethyl_butanoate.to_numpy()

array([[-0.2       , -0.51308901,  0.25833333,  0.3       ,  0.09166667,
         1.        , -0.25373134, -1.        , -0.80736544, -0.64166667,
        -1.        , -1.        , -1.        ],
       [-0.99444444, -1.        , -0.85277778, -0.99722222, -1.        ,
         0.74166667, -1.        , -0.70277778, -0.01944444,  0.53333333,
         0.15277778, -0.42222222, -1.        ],
       [-0.975     , -1.        , -0.36875   , -0.26666667, -0.74791667,
        -0.24583333, -0.88958333, -0.58958333, -0.5125    , -0.31875   ,
        -0.84166667, -0.75416667, -0.81666667]])

In [8]:
selected_columns = sagar_ds.loc[:, 'Fishy':'Spicy']
matrix = selected_columns.to_numpy()


(array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.70840278, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.855625  ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.  

In [ ]:
find_coarse_similarity(matrix, matrix)

In [9]:
find_finegrained_similarity(matrix,matrix)

array([[1.        , 1.        , 0.68751736, ..., 0.04963113, 0.43888012,
        0.63534808],
       [0.94300479, 1.        , 0.82506944, ..., 0.31673337, 0.41326531,
        1.        ],
       [1.        , 1.        , 0.41269494, ..., 1.        , 0.38734178,
        0.60255946],
       ...,
       [1.        , 0.14535156, 0.89460069, ..., 0.09251736, 0.140625  ,
        1.        ],
       [0.0625    , 0.03594184, 0.41173611, ..., 0.03135851, 0.46410156,
        0.28001736],
       [0.25      , 0.18958767, 0.21777778, ..., 0.37515625, 0.06354601,
        0.06354601]])

In [ ]:
# Categorization of the data based on fine-grained and coarse-level labels

In [24]:
base_dir = '/local_storage/datasets/farzaneh/alignment_olfaction_datasets/'

In [25]:
parent_input_sagar_original = base_dir+'NEMO_scripts-master/Data/supporting_files/NEMO_s01/Fullmet_FIR.mat'
data_original = sio.loadmat(parent_input_sagar_original)

In [26]:
parent_input_sagar_original = base_dir+'NEMO_scripts-master/Data/odor_responses_S1-3_regionized/odor_responses_S1.mat'
data1 = sio.loadmat(parent_input_sagar_original)
parent_input_sagar_original = base_dir+'NEMO_scripts-master/Data/odor_responses_S1-3_regionized/odor_responses_S2.mat'
data2 = sio.loadmat(parent_input_sagar_original)
parent_input_sagar_original = base_dir+'NEMO_scripts-master/Data/odor_responses_S1-3_regionized/odor_responses_S3.mat'
data3 = sio.loadmat(parent_input_sagar_original)

In [8]:
rois_all=  []
for data_s in [data1,data2,data3]:
    rois = {}
    rois['PirF']= data_s['odor_vals'][0][0]
    rois['PirT']= data_s['odor_vals'][0][1]
    rois['AMY']= data_s['odor_vals'][0][2]
    rois['OFC']= data_s['odor_vals'][0][3]
    rois_all.append(rois)


In [9]:
for rois in rois_all:
    for key in rois.keys():
        roi=rois[key]
        roi = np.moveaxis(roi,-1,0)
        # roi = np.mean(roi,-1)
        rois[key]=roi

In [13]:
def prepare_dataset(ds):
    # ds['y'] = ds['y'].apply(ast.literal_eval)
    ds['embeddings'] = ds['embeddings'].apply(ast.literal_eval)
    return ds

In [14]:
def custom_linear_regression(X,y):
    clf = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1])    
    estimator= clf.fit(X,y)
    return estimator

In [18]:
parent_input_sagar = base_dir+'curated_datasets/mols_datasets/curated_sagar_subjects_nonaminus.csv'
sagar_mols = pd.read_csv(parent_input_sagar)


In [39]:
def explainable_variance(data, bias_correction=True, do_zscore=True):
    """Compute explainable variance for a set of voxels.

    Parameters
    ----------
    data : array of shape (n_repeats, n_times, n_voxels)
        fMRI responses of the repeated test set.
    bias_correction: bool
        Perform bias correction based on the number of repetitions.
    do_zscore: bool
        z-score the data in time. Only set to False if your data time courses
        are already z-scored.

    Returns
    -------
    ev : array of shape (n_voxels, )
        Explainable variance per voxel.
    """
    if do_zscore:
        data = scipy.stats.zscore(data, axis=1)

    mean_var = data.var(axis=1, dtype=np.float64, ddof=1).mean(axis=0)
    var_mean = data.mean(axis=0).var(axis=0, dtype=np.float64, ddof=1)
    ev = var_mean / mean_var

    if bias_correction:
        n_repeats = data.shape[0]
        ev = ev - (1 - ev) / (n_repeats - 1)
    return ev


In [27]:
# sagar_mols1 = sagar_mols.loc[sagar_mols['subject']==1].sort_values('cid')
# sagar_mols2 = sagar_mols.loc[sagar_mols['subject']==2].sort_values('cid')
# sagar_mols3 = sagar_mols.loc[sagar_mols['subject']==3].sort_values('cid')

sagar_mols1 = sagar_mols.loc[sagar_mols['subject']==1]
sagar_mols2 = sagar_mols.loc[sagar_mols['subject']==2]
sagar_mols3 = sagar_mols.loc[sagar_mols['subject']==3]

In [ ]:
fmri_data_y=rois_all[:]['PirF']
# fmri_data_y = np.expand_dims(fmri_data_y.mean(-1),0)
print("(n_repeats, n_samples_test, n_voxels) =", fmri_data_y.shape)
ev = explainable_variance(fmri_data_y)
print("(n_voxels,) =", ev.shape)

# plotting the explainable variance

In [ ]:
voxel_1 = np.argmax(ev)
time = np.arange(Y_test.shape[1]) * 2  # one time point every 2 seconds
plt.figure(figsize=(10, 3))
plt.plot(time, Y_test[:, :, voxel_1].T, color='C0', alpha=0.5)
plt.plot(time, Y_test[:, :, voxel_1].mean(0), color='C1', label='average')
plt.xlabel("Time (sec)")
plt.title("Voxel with large explainable variance (%.2f)" % ev[voxel_1])
plt.yticks([])
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
voxel_2 = np.argmin(ev)
plt.figure(figsize=(10, 3))
plt.plot(time, Y_test[:, :, voxel_2].T, color='C0', alpha=0.5)
plt.plot(time, Y_test[:, :, voxel_2].mean(0), color='C1', label='average')
plt.xlabel("Time (sec)")
plt.title("Voxel with low explainable variance (%.2f)" % ev[voxel_2])
plt.yticks([])
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
plt.hist(ev, bins=np.linspace(0, 1, 100), log=True, histtype='step')
plt.xlabel("Explainable variance")
plt.ylabel("Number of voxels")
plt.title('Histogram of explainable variance')
plt.grid('on')
plt.show()